### ISSUE TITLE
Exception causing low FPS

### ISSUE THREAD

**Issue by BhasitL** [maruohon/minihud#393]
I get the following errors when looking at entities since I upgraded to Minecraft 1.21.5 as shown in the attached pictures. I have enabled this info lines and sometimes it works while sometimes it don't and causes FPS to drop immediately by almost 80% with lag:
infoLookingAtEntity: exception
infoLookingAtPlayerExp: exception
infoEntityVariant:exception

The server has Servux 0.6.0 and the client has MiniHUD 0.35.1 alongside MaLiLib 0.24.1 installed.

![Image](https://github.com/user-attachments/assets/489a7181-dc8e-42ed-9912-766ee50484e8)

**Comment by mercifulbird** [comment]
Can confirm, the issue is almost guaranteed to happen when an entity is unleashed. Minihud will also display attributes the entity does not have as exceptions e.g. horse stats, zombie villager conversion, etc.

**Comment by sakura-ryoko** [comment]
This was fixed in the 1.21.6 version.  I have yet to back port the "fixes" to 1.21.5; unless you are intending to upgrade to 1.21.7 when it comes out.

**Comment by BhasitL** [comment]
> This was fixed in the 1.21.6 version. I have yet to back port the "fixes" to 1.21.5; unless you are intending to upgrade to 1.21.7 when it comes out.

I have been using the 1.21.6 version and the issue still occurs for my friend and I. I'll try to put a screenshot afterwards

**Comment by sakura-ryoko** [comment]
Anyways; this was happening when it was requesting Entity NBT from `entityDataSync` and not receiving it for various reasons at different times; and it not being handled properly.

**Comment by sakura-ryoko** [comment]
So yes -- a bug.

**Comment by Amara-Luna** [comment]
> This was fixed in the 1.21.6 version. I have yet to back port the "fixes" to 1.21.5; unless you are intending to upgrade to 1.21.7 when it comes out.

Hi, just confirming this issue still exists in **1.21.7**. The lag gets worse with more entity info lines shown. As a temporary fix, turning off some info lines helps.

My environment: MC 1.21.7, MiniHUD 0.36.3, MaLiLib 0.25.4.

**Comment by sakura-ryoko** [comment]
I've done more research and the main reason is something that Vanilla has changed when trying to obtain NBT tags from certain entities in certain situations; such as a Boat with a mob in it.

It's more likely when you have multiple entity-type Info Lines enabled.  There really isn't an easy fix if the issue stems from something Vanilla is doing differently; perhaps.

**Comment by sakura-ryoko** [comment]
You can also help "reduce" the effect if you configure your NBT Cache to have a longer Timeout.
