### ISSUE TITLE
Game crashes when clicking in the structuresRenderThrough button in the Config panel

### ISSUE THREAD

**Issue by javiersalcedo** [maruohon/minihud#80]
Mods versions: MaLiLib 0.10.0-dev.21+arne.1
MiniHUD 0.19.0-dev.20200813.013642

Game crashes when trying to change the structuresRenderThrough option in the configuration panel to turn it true or false. The option _does_ get changed after restarting

Crash log:
[main/FATAL]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:440) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:92) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:162) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:162) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1046) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at fi.dy.masa.minihud.hotkeys.KeyCallbacks.lambda$init$1(KeyCallbacks.java:35) ~[minihud-fabric-1.16.2-0.19.0-dev.20200813.013642.jar:?]
	at fi.dy.masa.malilib.config.options.ConfigBase.onValueChanged(ConfigBase.java:75) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.config.options.ConfigBoolean.setBooleanValue(ConfigBoolean.java:47) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.config.IConfigBoolean.toggleBooleanValue(IConfigBoolean.java:13) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.button.ConfigButtonBoolean.onMouseClickedImpl(ConfigButtonBoolean.java:21) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:92) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetContainer.onMouseClicked(WidgetContainer.java:64) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.onMouseClicked(WidgetListBase.java:110) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetListConfigOptionsBase.onMouseClicked(WidgetListConfigOptionsBase.java:47) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:97) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.GuiConfigsBase.onMouseClicked(GuiConfigsBase.java:192) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:185) ~[malilib-fabric-1.16.2-0.10.0-dev.21+arne.1.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:92) ~[intermediary-minecraft-1.16.2-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:435) ~[intermediary-minecraft-1.16.2-client.jar:?]
	... 26 more
---- Minecraft Crash Report ----

**Comment by maruohon** [comment]
For some reason I couldn't reproduce the crash (maybe it's related to class loading order?), but I uploaded a new build which should fix the crash, here: https://masa.dy.fi/mcmods/client_mods/
Let me know if it fixes it for you, and I'll upload it to CF as well then.

**Comment by javiersalcedo** [comment]
Still not working for me :/

To reproduce:
Open Minecraft and before entering any world go directly to MiniHUD configuration and click on the structuresRenderThrough button. It crashes the game for me every time

If you open Minecraft, create/open a world and _then_ you go to the MiniHUD configuration menu, it works correctly. 
If you create/open a world and then exit it, and then you go to MiniHUD configuration menu, it works correctly as well.

Files in /mod folder: 
MaLiLib 0.10.0-dev.21+arne.1.jar
MiniHUD 0.19.0-dev.20200815.144501
ModMenu 1.14.6+build.31
FabricAPI 0.18.0+build.397

Crash log:
[crash-2020-08-15_11.42.55-client.txt](https://github.com/maruohon/minihud/files/5078935/crash-2020-08-15_11.42.55-client.txt)

Let me know if I can help you with further testing

**Comment by maruohon** [comment]
Oh okay that explains how it tries to fetch the renderer instance before it has been created.

I uploaded another build, now it actually fixes the crash.
